### ISSUE TITLE
Slider not working

### ISSUE THREAD

**Issue by himani8** [Magestore/Bannerslider#2]
Hii..
I installed this module in magento2.
But it's not working.
When i try to check previews then it's also not working and taking too much time while adding slider

**Comment by zerokool12a8** [comment]
Hi Himani,
Because some file javascript of Bannerslider extension was'nt generated in folder <magento root>/pub/static/<area>/Magento/<theme>/en_US/, so you took too much time while adding slider. May be your Magento software is in default mode.  You should run the Magento software in developer mode when you’re extending or customizing it. You can use this command line to show current mode : 
php bin/magento deploy:mode:show 
If you want to change to developer mode, you can use this command : 
php bin/magento deploy:mode:set developer

**Comment by himani8** [comment]
Okkk, but now what to do with missing file. I have unable developer mode.

I downloaded files from git itself.

**Comment by NicolasAndersen** [comment]
Now you only need to change to developer mode and disabled cache, then reload your page. The missing files will be generate.
